# Generated by Django 5.2.4 on 2025-08-08 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shop_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
