# Generated by Django 5.2.4 on 2025-08-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('shop', '0003_shop_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
