# Generated by Django 5.2.4 on 2025-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_group',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('super_user', 'Super User'), ('programmer', 'Programmer'), ('ceo', 'CEO')], default=('user', 'Normal User')),
        ),
    ]
