# Generated by Django 5.2.4 on 2025-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_group_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('super_user', 'Super User'), ('programmer', 'Programmer'), ('ceo', 'CEO')], default='user', max_length=12),
        ),
    ]
